Feat/settlement
spraoi/model-storehouse pull request #14
Opened 2021-07-22 11:23 UTC by srinidhi-spraoi

2021-07-23 13:46 UTC, jdecorte-spraoi requested changes
Just a note, please use more meaningful commit comments.  "In Progress", "Data Folder" are not good examples of commit messages.

2021-07-23 13:46 UTC, jdecorte-spraoi commented on model_settlement/model_settlement/helpers.py
> +                df.loc[:, col] = pd.to_datetime(df.loc[:, col], errors="coerce")
Can you just do the errors="coerce" every time instead?  If you need the try/except then add the specific exception.  Broad except clauses should be avoided.

2021-07-23 13:46 UTC, jdecorte-spraoi commented on model_settlement/model_settlement/helpers.py
> +        elif col == "prognosis_days":
No need for if/elsif.  Just check `if col == "prognosis_days": pass  else: process other cols`.

2021-07-23 13:46 UTC, jdecorte-spraoi commented on model_settlement/model_settlement/helpers.py
> +    COL = "Primary Diagnosis Category"
Just a suggestion:  It helps to use better variable names even for constants.  COL is a very vague name in this example.  You could use PRIMARY_DIAG_CAT for example.

2021-07-23 13:46 UTC, jdecorte-spraoi commented on model_settlement/model_settlement/helpers.py
> +
Single line functions are less valuable unless they are called multiple times.  If only called once, it is better just to leave the code in-line and not create a function for it.

2021-07-23 13:46 UTC, jdecorte-spraoi commented on model_settlement/model_settlement/predict.py
> +    label_data = pd.read_csv("data/settlement_labels.csv")  # may not be needed
What is the purpose of this huge file?  It appears to contain a lot of data that isn't used.  I only see the claim number being used.  Including in a file of this size could impact the install in the virtual env.  Can you just get a list of the claim numbers as a constant defined in the code?

2021-07-23 13:46 UTC, jdecorte-spraoi commented on model_settlement/pyproject.toml
> +
If we have to include the huge file, then you will need to add it here.  I don't know if it will get installed otherwise.

[Poetry Include](https://python-poetry.org/docs/pyproject/#include-and-exclude)

2021-07-26 06:55 UTC, srinidhi-spraoi commented on model_settlement/model_settlement/predict.py
> +    label_data = pd.read_csv("data/settlement_labels.csv")  # may not be needed
It was included to exclude claims already scored. Removed the file for now. We'll need a different way to exclude claims which are already scored (getting it from api instead of hardcoding it, for example). We can get to it when we have more info from FINEOS on the integration

2021-07-26 06:55 UTC, srinidhi-spraoi commented on model_settlement/pyproject.toml
> +
removed the file

2021-07-26 06:55 UTC, srinidhi-spraoi commented on model_settlement/model_settlement/helpers.py
> +
done

2021-07-26 06:57 UTC, srinidhi-spraoi commented on model_settlement/model_settlement/helpers.py
> +                df.loc[:, col] = pd.to_datetime(df.loc[:, col], errors="coerce")
done

2021-07-26 06:59 UTC, srinidhi-spraoi commented on model_settlement/model_settlement/helpers.py
> +        elif col == "prognosis_days":
removed the unused function

2021-07-26 06:59 UTC, srinidhi-spraoi commented on model_settlement/model_settlement/helpers.py
> +    COL = "Primary Diagnosis Category"
done

2021-07-26 13:27 UTC, jdecorte-spraoi approved these changes

2021-07-26 13:27 UTC, merged